import React from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './ui/navbar/navbar';
import Providers from './progressProdider';
import Footer from './ui/footer/footer';
import { LanguageProvider } from './languageContextProvider'; // Import LanguageProvider
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <LanguageProvider>
                        <Navbar />
                        {children}
                        <Footer />
                    </LanguageProvider>
                </Providers>
            </body>
        </html>
    );
}
